### ISSUE TITLE
Compatibility with v11

### ISSUE THREAD

**Issue by dggomes** [saif-ellafi/foundryvtt-sidebar-resizer#8]
Hi! It looks like the current release isn't compatible with v11. When I try to install it it gives me this error: Unable to load valid module: Module validation errors: author 1:name may not be undefined 0: name: may not be undefined.

Is there an easy fix?

Thanks!

**Comment by nschoenwald** [comment]
I would also love to see an update to this module!

**Comment by esheyw** [comment]
This module seems to work just fine in v11, with a couple manifest tweaks:
change `"authors": ["JeansenVaars", "Vance Cole"],` to
```
"authors": [
    {
      "name": "JeansenVaars",
      "flags": {}
    },
    {
      "name": "Vance Cole",
      "flags": {}
    }
  ],
  ```
and change the compatibility maximum to 11, or remove it. trying to update will still make foundry complain, but you can just lock the module for now until it gets updated here. sidebar resizing works fine.

**Comment by saif-ellafi** [comment]
Hi @dggomes @esheyw @chaoticnote @nschoenwald 
Updated for Foundry V11! 
Enjoy and let me know if you notice anything weird

**Comment by nschoenwald** [comment]
Thank you for the update, will let you know if I come across anything!

Saif Addin ***@***.***> schrieb am Di., 20. Juni 2023, 19:26:
